export const themeStyles = {
    mainColor: '#365070',
    textColor: 'rgb(46, 46, 46)',
    headingColor: 'rgb(46, 46, 46)',
    textColorAccent: '#fff',
    linkColor: 'rgb(230, 211, 65)',
    accentBackgroundColor: '#000',
    accentColor2: 'rgb(230, 211, 65)',
    altColor: 'rgb(230, 211, 65)',
    headerBackground: 'rgb(64,64,64)',
    footerBackground: 'linear-gradient(rgb(54,80,112, 0.6) 0%, rgb(54,80,112) 23%)',
    navBackground: 'rgb(64,64,64,.9)',
    BckdHeaderSocial: '#12343d',
    NavText: 'rgba(237,237,223,1)',
    subHeadingColor: '#5b5b5b',
    footerText: '#fff',
}

export const social = [
    {
        id: 1,
        name: 'facebook',
        format: 'http://www.facebook.com/%s',
        label: 'Facebook',
        value: 'Tipsyburro',
        enabled: 1,
        input: ['http://www.facebook.com/', ''],
        url: 'http://www.facebook.com/Tipsyburro',
    },
    {
        id: 2,
        name: 'twitter',
        format: 'http://www.twitter.com/%s',
        label: 'Twitter',
        value: 'cbs',
        enabled: 1,
        input: ['http://www.twitter.com/', ''],
        url: 'http://www.twitter.com/cbs',
    },
    {
        id: 16,
        name: 'custom-social-1',
        format: '',
        label: 'Stars',
        value: 'facebook.com',
        enabled: 1,
        input: null,
        url: 'facebook.com',
    },
]
