import { ThemeStyles } from 'types'

export const themeStyles: ThemeStyles = {
    logoColor: '#00c2d8',
    headingColor: '#66665e',
    subHeadingColor: '#5b5b5b',
    textColor: '#717171',
    linkColor: '#7c237a',
    linkHover: '#009374',
    btnText: '#ffffff',
    btnBackground: '#009374',
    textColorAccent: '#ffffff',
    heroSubheadline: '#ffffff',
    heroText: '#ca0202',
    heroBtnText: '#fafaeb',
    heroBtnBackground: '#00c2d8',
    heroLink: '#DDDDDD',
    heroLinkHover: 'transparent',
    captionText: 'rgba(250,250,235,1)',
    captionBackground: 'rgba(0,194,216,1)',
    NavText: 'rgba(237,237,223,1)',
    navHover: '#009374',
    navCurrent: 'rgba(0,194,216,1)',
    backgroundMain: 'rgba(0,0,0,.2)',
    bckdContent: 'rgba(255,255,255,1)',
    headerBackground: 'rgba(16,37,46,1)',
    BckdHeaderSocial: '#12343d',
    accentBackgroundColor: '#12343d',
    backgroundHero: '#ffc83d',
    footerBackground: 'rgba(16,37,46,1)',
    footerText: '#dbf8ff',
    footerLink: '#dbf8ff',
    promoText: '#ffffff',
    promoColor: '#3eb183',
    promoColor2: '#00a4fc',
    promoColor3: '#3eb183',
    promoColor4: '#e02aa0',
    promoColor5: '#30829b',
    promoColor6: '#10252e',
}

export const social = [
    {
        id: 1,
        name: 'facebook',
        format: 'http://www.facebook.com/%s',
        label: 'Facebook',
        value: 'Tipsyburro',
        enabled: 1,
        input: ['http://www.facebook.com/', ''],
        url: 'http://www.facebook.com/Tipsyburro',
        icon: ['fas', 'Rocket'],
    },
    {
        id: 2,
        name: 'twitter',
        format: 'http://www.twitter.com/%s',
        label: 'Twitter',
        value: 'cbs',
        enabled: 1,
        input: ['http://www.twitter.com/', ''],
        url: 'http://www.twitter.com/cbs',
        icon: ['fas', 'Rocket'],
    },
]

export const buttonList1 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_1',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
    },
    {
        name: 'btn2',
        link: '/banner/',
        window: '',
        label: 'Button2',
        active: false,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
    },
]

export const buttonList2 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_1',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
    },
    {
        name: 'btn2',
        link: '/banner/',
        window: '',
        label: 'Button2',
        active: true,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
    },
]

export const buttonListJust2 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
    },
]
