import { ThemeStyles } from 'types'

export const themeStyles: ThemeStyles = {
    logoColor: '#00c2d8',
    headingColor: '#66665e',
    subHeadingColor: '#5b5b5b',
    textColor: '#717171',
    linkColor: '#7c237a',
    linkHover: '#009374',
    btnText: '#ffffff',
    btnBackground: '#009374',
    textColorAccent: '#ffffff',
    heroSubheadline: '#ffffff',
    heroText: '#ca0202',
    heroBtnText: '#fafaeb',
    heroBtnBackground: '#00c2d8',
    heroLink: '#DDDDDD',
    heroLinkHover: 'transparent',
    captionText: 'rgba(250,250,235,1)',
    captionBackground: 'rgba(0,194,216,1)',
    NavText: 'rgba(237,237,223,1)',
    navHover: '#009374',
    navCurrent: 'rgba(0,194,216,1)',
    backgroundMain: 'rgba(0,0,0,.2)',
    bckdContent: 'rgba(255,255,255,1)',
    headerBackground: 'rgba(16,37,46,1)',
    BckdHeaderSocial: '#12343d',
    accentBackgroundColor: '#12343d',
    backgroundHero: '#ffc83d',
    footerBackground: 'rgba(16,37,46,1)',
    footerText: '#dbf8ff',
    footerLink: '#dbf8ff',
    promoText: '#ffffff',
    promoColor: '#3eb183',
    promoColor2: '#00a4fc',
    promoColor3: '#3eb183',
    promoColor4: '#e02aa0',
    promoColor5: '#30829b',
    promoColor6: '#10252e',
}

export const social = [
    {
        id: 1,
        name: 'facebook',
        format: 'http://www.facebook.com/%s',
        label: 'Facebook',
        value: 'Tipsyburro',
        enabled: 1,
        input: ['http://www.facebook.com/', ''],
        url: 'http://www.facebook.com/Tipsyburro',
        icon: ['fas', 'Rocket'],
    },
    {
        id: 2,
        name: 'twitter',
        format: 'http://www.twitter.com/%s',
        label: 'Twitter',
        value: 'cbs',
        enabled: 1,
        input: ['http://www.twitter.com/', ''],
        url: 'http://www.twitter.com/cbs',
        icon: ['fas', 'Rocket'],
    },
]

export const buttonList1 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_1',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
        opensModal: -1,
    },
    {
        name: 'btn2',
        link: '/banner/',
        window: '',
        label: 'Button2',
        active: false,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
        opensModal: -1,
    },
]

export const buttonList2 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_1',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
        opensModal: -1,
    },
    {
        name: 'btn2',
        link: '/banner/',
        window: '',
        label: 'Button2',
        active: true,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
        opensModal: -1,
    },
]

export const buttonListJust2 = [
    {
        name: 'btn1',
        link: '/article/',
        window: '',
        label: 'Button1',
        active: true,
        btnType: 'btn_2',
        btnSize: 'btn_md',
        linkType: 'local',
        blockBtn: false,
        opensModal: -1,
    },
]

export const img1 = 'https://townsquareinteractive.s3.amazonaws.com/global-assets/images/bellagioFountain1.jpg'
export const img2 = 'https://townsquareinteractive.s3.amazonaws.com/global-assets/images/birdlake.jpg'

export const siteDataEx = {
    logos: {
        fonts: [],
        footer: {
            pct: 100,
            slots: [
                {
                    show: 1,
                    type: 'image',
                    markup: '',
                    hasLinks: false,
                    alignment: 'left',
                    image_src: 'img1',
                    image_link: '/',
                },
            ],
            activeSlots: [0],
        },
        header: {
            pct: 100,
            slots: [
                {
                    show: 1,
                    type: 'image',
                    markup: '',
                    hasLinks: false,
                    alignment: 'right',
                    image_src: 'img2',
                    image_link: '/',
                },
                {
                    show: 0,
                    type: 'image',
                    markup: '',
                    hasLinks: false,
                    alignment: 'right',
                    image_src: '',
                    image_link: '/',
                },
                {
                    show: 0,
                    type: 'image',
                    markup: '',
                    hasLinks: false,
                    alignment: 'right',
                    image_src: '',
                    image_link: '/',
                },
            ],
            activeSlots: [0],
        },
        mobile: {
            pct: 100,
            slots: [
                {
                    show: 1,
                    type: 'image',
                    markup: '',
                    hasLinks: false,
                    alignment: 'left',
                    image_src: 'img1',
                    image_link: '/article/',
                    image_link_ext: '',
                },
            ],
            activeSlots: [0],
        },
        list: {
            '4763981': '/files/2022/07/jremodeling-logo.png',
            '4999935': '/files/2022/09/Yos2.jpg',
            '5069847': '/files/2022/10/screen-8.jpg',
        },
    },
    footerLogos: {
        show: 1,
        type: 'image',
        markup: '',
        hasLinks: false,
        alignment: 'left',
        image_src: 'img1',
        image_link: '/',
    },
    social: [
        {
            id: 1,
            name: 'facebook',
            format: 'http://www.facebook.com/%s',
            label: 'Facebook',
            value: 'Tipsyburr',
            enabled: 1,
            input: ['http://www.facebook.com/', ''],
            url: 'http://www.facebook.com/Tipsyburr',
            icon: ['fab', 'facebook'],
        },
        {
            id: 2,
            name: 'twitter',
            format: 'http://www.twitter.com/%s',
            label: 'Twitter',
            value: 'cbs',
            enabled: 1,
            input: ['http://www.twitter.com/', ''],
            url: 'http://www.twitter.com/cbs',
            icon: ['fab', 'twitter'],
        },
    ],
    contact: {
        email: [
            {
                name: 'Email2',
                email: 'email@email.com',
                disabled: '',
                isPrimaryEmail: true,
            },
        ],
        hours: {
            friday: '9:00AM-5:00PM',
            monday: '9:00AM-5:00PM',
            sunday: '',
            tuesday: '9:00AM-5:00PM',
            saturday: '',
            thursday: '9:00AM-5:00PM',
            wednesday: '9:00AM-5:00PM',
        },
        phone: [
            {
                name: 'Phone',
                number: '(919) 540-0392',
                disabled: '',
                isPrimaryPhone: true,
            },
        ],
        address: {
            zip: '28204',
            city: 'Charlotte',
            name: 'Charlotte Site3',
            state: 'NC',
            street: '3310 North Davidson St',
            street2: '',
        },
        //hideZip: false,
        /* advanced: {
        lat: '',
        long: '',
    },
    disabled: '',
    hideCity: false,
    hideState: false,
    isPrimary: true,
    hideAddress: false,
    displayInMap: true,
    hideAddress2: false,
    displayInFooter: true, */
        /* selectedPrimaryEmailLabel: 'Email2',
    selectedPrimaryPhoneLabel: '',
    selectedPrimaryPhoneNumber: '2343423432',
    selectedPrimaryEmailAddress: 'NExtEmail@email.com', */
        displayInMap: true,
        contactLinks: [
            {
                cName: 'phone',
                link: 'tel:(919) 540-0392',
                icon: ['fas', 'phone'],
                content: '(919) 540-0392',
                active: true,
            },
            {
                cName: 'email',
                link: 'mailto:email@email.com',
                icon: ['fas', 'envelope'],
                content: 'Email2: email@email.com',
                active: true,
            },
            {
                cName: 'map',
                link: 'https://www.google.com/maps/place/3310+North+Davidson+St+28204',
                icon: ['fas', 'location-pin'],
                content: 'Charlotte Site3',
                active: true,
            },
        ],
        showContactBox: false,
    },
    siteName: 'Charlotte Sites',
    phoneNumber: '2343423432',
    email: 'NExtEmail@email.com',
    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com',
    composites: {},
    cmsNav: [
        {
            ID: 712524,
            menu_list_id: 62387,
            title: 'Home',
            post_type: 'nav_menu_item',
            type: null,
            menu_item_parent: 0,
            object_id: 641788,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 1,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/',
            submenu: [],
            slug: 'home',
        },
        {
            ID: 712607,
            menu_list_id: 62387,
            title: 'Article',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 641863,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 2,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/article/',
            submenu: [
                {
                    ID: 723348,
                    menu_list_id: 62387,
                    title: 'columns',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 712607,
                    object_id: 651535,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 3,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/columns/',
                    submenu: [],
                    slug: 'columns',
                },
            ],
            slug: 'article',
        },
        {
            ID: 733409,
            menu_list_id: 62387,
            title: 'newcolumns',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 660622,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 4,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/newcolumns/',
            submenu: [
                {
                    ID: 765373,
                    menu_list_id: 62387,
                    title: 'other',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 733409,
                    object_id: 688906,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 5,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/other/',
                    submenu: [],
                    slug: 'other',
                },
            ],
            slug: 'newcolumns',
        },
        {
            ID: 772495,
            menu_list_id: 62387,
            title: 'good',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 695238,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 6,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/good/',
            submenu: [
                {
                    ID: 786045,
                    menu_list_id: 62387,
                    title: 'Test2',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 772495,
                    object_id: 707521,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 7,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/test2/',
                    submenu: [
                        {
                            ID: 775702,
                            menu_list_id: 62387,
                            title: 'Test',
                            post_type: 'nav_menu_item',
                            type: 'post_type',
                            menu_item_parent: 786045,
                            object_id: 698051,
                            object: 'page',
                            target: null,
                            classes: null,
                            menu_order: 8,
                            mi_url: null,
                            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/test/',
                            submenu: [],
                            slug: 'test',
                        },
                    ],
                    slug: 'test2',
                },
            ],
            slug: 'good',
        },
        {
            ID: 794358,
            menu_list_id: 62387,
            title: 'banner',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 714786,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 9,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/banner/',
            submenu: [],
            slug: 'banner',
        },
        {
            ID: 802444,
            menu_list_id: 62387,
            title: 'mix',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 721724,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 10,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/mix/',
            submenu: [
                {
                    ID: 734443,
                    menu_list_id: 62387,
                    title: 'new',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 802444,
                    object_id: 661579,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 11,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/new',
                    submenu: [],
                    slug: 'new',
                },
                {
                    ID: 794805,
                    menu_list_id: 62387,
                    title: 'Photo Grid',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 802444,
                    object_id: 715194,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 12,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/photo-grid/',
                    submenu: [
                        {
                            ID: 798076,
                            menu_list_id: 62387,
                            title: 'newpage',
                            post_type: 'nav_menu_item',
                            type: 'post_type',
                            menu_item_parent: 794805,
                            object_id: 717876,
                            object: 'page',
                            target: null,
                            classes: null,
                            menu_order: 13,
                            mi_url: null,
                            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/newpage/',
                            submenu: [],
                            slug: 'newpage',
                        },
                    ],
                    slug: 'photo-grid',
                },
                {
                    ID: 822994,
                    menu_list_id: 62387,
                    title: 'parallax',
                    post_type: 'nav_menu_item',
                    type: 'post_type',
                    menu_item_parent: 802444,
                    object_id: 739841,
                    object: 'page',
                    target: null,
                    classes: null,
                    menu_order: 14,
                    mi_url: null,
                    url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/parallax/',
                    submenu: [],
                    slug: 'parallax',
                },
            ],
            slug: 'mix',
        },
        {
            ID: 827402,
            menu_list_id: 62387,
            title: 'mods',
            post_type: 'nav_menu_item',
            type: 'post_type',
            menu_item_parent: 0,
            object_id: 743633,
            object: 'page',
            target: null,
            classes: null,
            menu_order: 15,
            mi_url: null,
            url: 'clttestsiteforjoshedwards.production.townsquareinteractive.com/mods/',
            submenu: [],
            slug: 'mods',
        },
    ],
    cmsColors: {
        logoColor: '#05cae0',
        headingColor: '#454545',
        subHeadingColor: '#454545',
        textColor: '#717171',
        linkColor: '#45ffd8',
        linkHover: '#40dcbc',
        btnText: '#ffffff',
        btnBackground: '#009374',
        textColorAccent: '#ffffff',
        heroSubheadline: '#ffffff',
        heroText: '#e00f0f',
        heroBtnText: '#fafaeb',
        heroBtnBackground: '#00c2d8',
        heroLink: '#DDDDDD',
        heroLinkHover: 'transparent',
        captionText: 'rgba(250,250,235,1)',
        captionBackground: 'rgba(0,194,216,.5)',
        NavText: 'rgba(237,237,223,1)',
        navHover: '#009374',
        navCurrent: '#d20000',
        backgroundMain: 'rgba(0,0,0,.2)',
        bckdContent: 'rgba(255,255,255,1)',
        headerBackground: 'rgba(16,37,46,1)',
        BckdHeaderSocial: '#12343d',
        accentBackgroundColor: '#12343d',
        backgroundHero: '#ffc83d',
        footerBackground: 'rgba(16,37,46,1)',
        footerText: '#dbf8ff',
        footerLink: '#dbf8ff',
        promoText: '#ffffff',
        promoColor: '#3eb183',
        promoColor2: '#00a4fc',
        promoColor3: '#c037dd',
        promoColor4: '#e02aa0',
        promoColor5: '#30829b',
        promoColor6: '#10252e',
    },
    theme: 'beacon-theme_charlotte',
    cmsUrl: 'clttestsiteforjoshedwards.production.townsquareinteractive.com',
    s3Folder: 'clttestsiteforjoshedwards',
    favicon: 'star.png',
    fontImport: ' body {font-family:Lato}\n    .hd-font{font-family:Lato} \n    .txt-font{font-family:Lato}\n    .feat-font{font-family:Josefin Sans}\n    ',
}

export const itemStyle = {
    borderStyle: { backgroundImage: 'linear-gradient(-45deg, #3eb183, #00a4fc)' },
    noImage: { background: '#3eb183' },
}

export const itemStyle2 = {
    borderStyle: { backgroundImage: 'linear-gradient(-45deg, #00A4FC, #cc00f9)' },
    noImage: { background: '#00A4FC' },
}

export const icon = { iconPrefix: 'far', iconModel: 'address-book' }

export const createStoryStyles = (themeStyles: ThemeStyles) => {
    const textColors = `.accent-txt{color:${themeStyles['textColorAccent']}} .txt-color{color:${themeStyles['textColor']}} .txt-color-hd{color:${themeStyles['headingColor']}}`

    const btnStyles = `.btn_1{color: ${themeStyles['textColorAccent']}; background-color: ${themeStyles['promoColor']}} .btn_1:hover{color: ${themeStyles['promoColor']}; background-color: ${themeStyles['textColorAccent']}} .btn_2{color: ${themeStyles['promoColor']}; border-color: ${themeStyles['promoColor']}} .btn_2:hover{color: ${themeStyles['textColorAccent']}; background-color: ${themeStyles['promoColor']}}`

    const colorStyles = textColors + btnStyles

    return colorStyles
}

export const imageSizes = {
    big: '100vw',
    testimonial: '130px',
    columns: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw',
    normal: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 1200px',
}
